### ISSUE TITLE
Support GLTF export

### ISSUE THREAD

**Issue by DustStock** [olitheolix/blender-convex-decomposition#7]
Greetings, I have modified your code to support GLTF which, in turn, better supports other engines like Godot.

Additionally, I have made some tweaks to the CoaCD options (I also corrected an unfortunate typo).

However, I have made these changes with only me in mind and they are kludgy. So, I don't want to open a pull request with it, because I do not think it matches the quality of your product.

However, I would love to share those changes with you so you can incorporate them. Let me know if you are interested.

BTW, love the plugin.

**Comment by olitheolix** [comment]
Hi @DustStock 

I have not used this plugin for a while myself but i am happy to hear it still works and that you like it.

I have no plans to work on this at the moment but you are welcome to open PRs to fix typos or expose more solver options.

**Comment by DustStock** [comment]
@olitheolix I have made some changes and opened a PR. I have it working for Blender 4.1.

I am considering adding a "manual" decomposition tab with some tools to make decompositions "by hand" a little easier.
